stages:
  - test

test_job:
  stage: test
  image: mcr.microsoft.com/playwright:v1.43.1-jammy
  script:
    - npm ci
    - npx playwright install
    - npx playwright test
  artifacts:
    paths:
      - test-results-html
    expire_in: 1 week
  when: always
